name: C/C++ CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-20.04


    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive
        token: ${{ secrets.CI_PAT }}
    - name: install deps
      run: sudo apt-get install libboost-all-dev
    - name: make clean all
      run: cd test && make clean all
    - name: generate docs
      run: cd docs && doxygen Doxyfile
    - name: commit docs
      run: |
        git config --global user.name 'auto'
        git config --global user.email 'cjd218@users.noreply.github.com'
        git commit -am "Automated Fault Tolerance Doc Update"
        git push
       
   
