name: C/C++ CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-20.04


    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive
        token: ${{ secrets.CI_PAT }}
    - name: install deps
      run: sudo apt-get update && sudo apt-get install libboost-all-dev tbb spdlog-devel libfabric
    - name: make clean all
      run: cd test && make clean all
       
   
